version: "3.7"

services:
  muzero-http:
    build: .
    volumes:
      - ./models/_for_test/tictactoe/model.checkpoint:/app/models/tictactoe/model.checkpoint
    environment:
      - MODEL_PATH_tictactoe=models/tictactoe/model.checkpoint
      - CUDA_VISIBLE_DEVICES=
    ports:
      - "8000:8000"